all:
  hosts:
    server02:
      ansible_host: 192.168.211.17
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./kpchongtest.pem

    # server03:
    # ansible_host: 192.168.211.18
    # ansible_user: ubuntu
    # ansible_ssh_private_key_file: ./kpchongtest.pem

